/* User */
export const ADD_USER = 'ADD_USER';
/* Asynchronous User */
export const UPDATE_USER_REQUESTED = 'UPDATE_USER_REQUESTED';
export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED';
export const CHECK_USER_REQUESTED = 'CHECK_USER_REQUESTED';
/* Called by sagas */
export const UPDATE_USER_SUCCEEDED = 'UPDATE_USER_SUCCEEDED';
export const DELETE_USER_SUCCEEDED = 'DELETE_USER_SUCCEEDED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
export const CHECK_USER_SUCCEEDED = 'CHECK_USER_SUCCEEDED';
export const CHECK_USER_FAILED = 'CHECK_USER_FAILED';

/* Modal */
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
