const constants = {
  permissions: {
    GROUP: {
      DELETE_USER: 'DELETE_USERS',
      DELETE_SELLER: 'DELETE_SELLER',
      DELETE_ADMIN: 'DELETE_ADMIN',
      ADD_ITEM: 'ADD_ITEM',
      DELETE_ITEM: 'DELETE_ITEM',
      DELETE_USER_ITEM: 'DELETE_USER_ITEM',
      DELETE_SELLER_ITEM: 'DELETE_SELLER_ITEM',
      DELETE_ADMIN_ITEM: 'DELETE_ADMIN_ITEM',
      CHANGE_ROLES: 'CHANGE_ROLES',
      EDIT_SETTINGS: 'EDIT_SETTINGS'
    }
  },
  errors: {
    GROUP_UPDATE: {
      DUPLICATE_URLSUFFIX: 'DUPLICATE_URLSUFFIX',
      NAME_TOO_SHORT: 'NAME_TOO_SHORT',
      NAME_TOO_LONG: 'NAME_TOO_LONG'
    }
  }
};

export default constants;
