const constants = {
  permissions: {
    GROUP: {
      DELETE_USER: 'DELETE_USERS',
      DELETE_SELLER: 'DELETE_SELLER',
      DELETE_ADMIN: 'DELETE_ADMIN',
      ADD_ITEM: 'ADD_ITEM',
      DELETE_ITEM: 'DELETE_ITEM',
      DELETE_USER_ITEM: 'DELETE_USER_ITEM',
      DELETE_SELLER_ITEM: 'DELETE_SELLER_ITEM',
      DELETE_ADMIN_ITEM: 'DELETE_ADMIN_ITEM',
      PROMOTE_USER_TO_SELLER: 'PROMOTE_USER_TO_SELLER',
      PROMOTE_SELLER_TO_ADMIN: 'PROMOTE_SELLER_TO_ADMIN',
      PROMOTE_USER_TO_ADMIN: 'PROMOTE_USER_TO_ADMIN',
      DEMOTE_ADMIN_TO_SELLER: 'DEMOTE_ADMIN_TO_SELLER',
      DEMOTE_ADMIN_TO_USER: 'DEMOTE_ADMIN_TO_USER',
      DEMOTE_SELLER_TO_USER: 'DEMOTE_SELLER_TO_USER',
      EDIT_SETTINGS: 'EDIT_SETTINGS'
    }
  }
};

export default constants;
