const constants = {
  PERMISSIONS: {
    GROUP: {
      DELETE_USER: 'DELETE_USER',
      DELETE_SELLER: 'DELETE_SELLER',
      DELETE_ADMIN: 'DELETE_ADMIN',
      ADD_ITEM: 'ADD_ITEM',
      DELETE_ITEM: 'DELETE_ITEM',
      DELETE_USER_ITEM: 'DELETE_USER_ITEM',
      DELETE_SELLER_ITEM: 'DELETE_SELLER_ITEM',
      DELETE_ADMIN_ITEM: 'DELETE_ADMIN_ITEM',
      CHANGE_ROLES: 'CHANGE_ROLES',
      EDIT_SETTINGS: 'EDIT_SETTINGS'
    }
  },
  ERRORS: {
    GROUP_ADD: {
      NAME_TOO_SHORT: 'NAME_TOO_SHORT',
      NAME_TOO_LONG: 'NAME_TOO_LONG',
      NAME_MISSING: 'NAME_MISSING',
      DESCRIPTION_TOO_LONG: 'DESCRIPTION_TOO_LONG',
      PERMISSIONS_INVALID: 'PERMISSIONS_INVALID',
      SETTINGS_INVALID: 'SETTINGS_INVALID',
      SETTINGS_MIN_PRICE_TOO_LOW: 'SETTINGS_MIN_PRICE_TOO_LOW',
      SETTINGS_MIN_PRICE_TOO_HIGH: 'SETTINGS_MIN_PRICE_TOO_HIGH',
      SETTINGS_MIN_PRICE_INVALID: 'SETTINGS_MIN_PRICE_INVALID',
      SETTINGS_DEFAULTROLE_INVALID: 'SETTINGS_DEFAULTROLE_INVALID',
      SETTINGS_DEFAULTROLE_MISSING: 'SETTINGS_DEFAULTROLE_MISSING',
      PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
      PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
      PASSWORD_INVALID: 'PASSWORD_INVALID',
      URLSUFFIX_TOO_SHORT: 'URLSUFFIX_TOO_SHORT',
      URLSUFFIX_TOO_LONG: 'URLSUFFIX_TOO_LONG',
      URLSUFFIX_MISSING: 'URLSUFFIX_MISSING',
      URLSUFFIX_DUPLICATE: 'URLSUFFIX_DUPLICATE',
      URLSUFFIX_INVALID: 'URLSUFFIX_INVALID',
      GROUP_EXISTS: 'GROUP_EXISTS'
    },
    GROUP_UPDATE: {
      NAME_TOO_SHORT: 'NAME_TOO_SHORT',
      NAME_TOO_LONG: 'NAME_TOO_LONG',
      NAME_MISSING: 'NAME_MISSING',
      DESCRIPTION_TOO_LONG: 'DESCRIPTION_TOO_LONG',
      PERMISSIONS_INVALID: 'PERMISSIONS_INVALID',
      SETTINGS_INVALID: 'SETTINGS_INVALID',
      SETTINGS_MIN_PRICE_TOO_LOW: 'SETTINGS_MIN_PRICE_TOO_LOW',
      SETTINGS_MIN_PRICE_TOO_HIGH: 'SETTINGS_MIN_PRICE_TOO_HIGH',
      SETTINGS_MIN_PRICE_INVALID: 'SETTINGS_MIN_PRICE_INVALID',
      SETTINGS_DEFAULTROLE_INVALID: 'SETTINGS_DEFAULTROLE_INVALID',
      SETTINGS_DEFAULTROLE_MISSING: 'SETTINGS_DEFAULTROLE_MISSING',
      PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
      PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
      PASSWORD_INVALID: 'PASSWORD_INVALID',
      URLSUFFIX_TOO_SHORT: 'URLSUFFIX_TOO_SHORT',
      URLSUFFIX_TOO_LONG: 'URLSUFFIX_TOO_LONG',
      URLSUFFIX_MISSING: 'URLSUFFIX_MISSING',
      URLSUFFIX_DUPLICATE: 'URLSUFFIX_DUPLICATE',
      URLSUFFIX_INVALID: 'URLSUFFIX_INVALID',
      DEFAULTROLE_INVALID: 'DEFAULTROLE_INVALID',
      ITEMS_MISSING: 'ITEMS_MISSING',
      ITEM_ADDED_INVALID: 'ITEM_ADDED_INVALID',
      ITEM_DELETED_INVALID: 'ITEM_DELETED_INVALID',
      USER_DELETED_NO_PRIVILEGES: 'USER_DELETED_NO_PRIVILEGES',
      USERS_MISSING: 'USERS_MISSING',
      USER_DELETED_INVALID: 'USER_DELETED_INVALID',
      UNPRIVILEGED: 'UNPRIVILEGED',
      GROUP_NOT_FOUND: 'GROUP_NOT_FOUND'
    },
    ITEM_UPDATE: {
      NAME_TOO_SHORT: 'NAME_TOO_SHORT',
      NAME_TOO_LONG: 'NAME_TOO_LONG',
      NAME_MISSING: 'NAME_MISSING',
      DESCRIPTION_TOO_SHORT: 'DESCRIPTION_TOO_SHORT',
      DESCRIPTION_TOO_LONG: 'DESCRIPTION_TOO_LONG',
      PRICE_TOO_LOW: 'PRICE_TOO_LOW',
      PRICE_TOO_HIGH: 'PRICE_TOO_HIGH',
      PRICE_INVALID: 'PRICE_INVALID',
      AMOUNT_TOO_LOW: 'AMOUNT_TOO_LOW',
      AMOUNT_TOO_HIGH: 'AMOUNT_TOO_HIGH',
      AMOUNT_INVALID: 'AMOUNT_INVALID',
      GROUP_CANNOT_ADD: 'GROUP_CANNOT_ADD',
      GROUP_CANNOT_REMOVE: 'GROUP_CANNOT_REMOVE'
    }
  },
  ROLES: {
    OWNER: 'OWNER',
    ADMIN: 'ADMIN',
    SELLER: 'SELLER',
    BUYER: 'BUYER'
  },
  ACTIONS: {
    GROUP: {
      EDIT_NAME: 'EDIT_NAME',
      ADD_DESCRIPTION: 'ADD_DESCRIPTION',
      EDIT_DESCRIPTION: 'EDIT_DESCRIPTION',
      DELETE_DESCRIPTION: 'DELETE_DESCRIPTION',
      ADD_PASSWORD: 'ADD_PASSWORD',
      EDIT_PASSWORD: 'EDIT_PASSWORD',
      DELETE_PASSWORD: 'DELETE_PASSWORD',
      EDIT_URLSUFFIX: 'EDIT_URLSUFFIX',
      EDIT_ADMIN_PERMISSIONS: 'EDIT_ADMIN_PERMISSIONS',
      EDIT_SELLER_PERMISSIONS: 'EDIT_SELLER_PERMISSIONS',
      EDIT_USER_PERMISSIONS: 'EDIT_USER_PERMISSIONS',
      EDIT_SETTINGS_PRICE_LIMIT: 'EDIT_SETTINGS_PRICE_LIMIT',
      EDIT_SETTINGS_DEFAULT_ROLE: 'EDIT_SETTINGS_DEFAULT_ROLE',
      DELETE_ITEM: 'REMOVE_ITEM',
      ADD_ITEM: 'ADD_ITEM',
      DELETE_USER: 'DELETE_USER'
    }
  }
};

export default constants;
