export const MODAL_IDS = {
  AUTH: 'LOGIN_REGISTER_MODAL',
  NEW_PRODUCT: 'SELL_PRODUCT_MODAL'
};

export const PERMISSIONS = {
  GROUP: {
    ALL: 'ALL',
    DELETE_USER: 'DELETE_USER',
    DELETE_SELLER: 'DELETE_SELLER',
    DELETE_ADMIN: 'DELETE_ADMIN',
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    DELETE_USER_ITEM: 'DELETE_USER_ITEM',
    DELETE_SELLER_ITEM: 'DELETE_SELLER_ITEM',
    DELETE_ADMIN_ITEM: 'DELETE_ADMIN_ITEM',
    CHANGE_ROLES: 'CHANGE_ROLES',
    EDIT_SETTINGS: 'EDIT_SETTINGS'
  }
};

export const ERRORS = {
  GROUP_ADD: {
    NAME_TOO_SHORT: 'NAME_TOO_SHORT',
    NAME_TOO_LONG: 'NAME_TOO_LONG',
    NAME_MISSING: 'NAME_MISSING',
    DESCRIPTION_TOO_LONG: 'DESCRIPTION_TOO_LONG',
    PERMISSIONS_INVALID: 'PERMISSIONS_INVALID',
    SETTINGS_INVALID: 'SETTINGS_INVALID',
    SETTINGS_MIN_PRICE_TOO_LOW: 'SETTINGS_MIN_PRICE_TOO_LOW',
    SETTINGS_MIN_PRICE_TOO_HIGH: 'SETTINGS_MIN_PRICE_TOO_HIGH',
    SETTINGS_MIN_PRICE_INVALID: 'SETTINGS_MIN_PRICE_INVALID',
    SETTINGS_DEFAULTROLE_INVALID: 'SETTINGS_DEFAULTROLE_INVALID',
    SETTINGS_DEFAULTROLE_MISSING: 'SETTINGS_DEFAULTROLE_MISSING',
    PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
    PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
    PASSWORD_INVALID: 'PASSWORD_INVALID',
    URLSUFFIX_TOO_SHORT: 'URLSUFFIX_TOO_SHORT',
    URLSUFFIX_TOO_LONG: 'URLSUFFIX_TOO_LONG',
    URLSUFFIX_MISSING: 'URLSUFFIX_MISSING',
    URLSUFFIX_DUPLICATE: 'URLSUFFIX_DUPLICATE',
    URLSUFFIX_INVALID: 'URLSUFFIX_INVALID',
    GROUP_EXISTS: 'GROUP_EXISTS'
  },
  GROUP_UPDATE: {
    NAME_TOO_SHORT: 'NAME_TOO_SHORT',
    NAME_TOO_LONG: 'NAME_TOO_LONG',
    NAME_MISSING: 'NAME_MISSING',
    DESCRIPTION_TOO_SHORT: 'DESCRIPTION_TOO_SHORT',
    DESCRIPTION_TOO_LONG: 'DESCRIPTION_TOO_LONG',
    PERMISSIONS_INVALID: 'PERMISSIONS_INVALID',
    SETTINGS_INVALID: 'SETTINGS_INVALID',
    SETTINGS_MIN_PRICE_TOO_LOW: 'SETTINGS_MIN_PRICE_TOO_LOW',
    SETTINGS_MIN_PRICE_TOO_HIGH: 'SETTINGS_MIN_PRICE_TOO_HIGH',
    SETTINGS_MIN_PRICE_INVALID: 'SETTINGS_MIN_PRICE_INVALID',
    PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
    PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
    PASSWORD_INVALID: 'PASSWORD_INVALID',
    URLSUFFIX_TOO_SHORT: 'URLSUFFIX_TOO_SHORT',
    URLSUFFIX_TOO_LONG: 'URLSUFFIX_TOO_LONG',
    URLSUFFIX_MISSING: 'URLSUFFIX_MISSING',
    URLSUFFIX_DUPLICATE: 'URLSUFFIX_DUPLICATE',
    URLSUFFIX_INVALID: 'URLSUFFIX_INVALID',
    DEFAULTROLE_INVALID: 'DEFAULTROLE_INVALID',
    ITEM_DELETE_NO_PRIVILEGES: 'ITEM_DELETE_NO_PRIVILEGES',
    ITEM_ADD_NO_PRIVILEGES: 'ITEM_ADD_NO_PRIVILEGES'
  },
  ITEM_UPDATE: {
    NAME_TOO_SHORT: 'NAME_TOO_SHORT',
    NAME_TOO_LONG: 'NAME_TOO_LONG',
    NAME_MISSING: 'NAME_MISSING',
    DESCRIPTION_TOO_SHORT: 'DESCRIPTION_TOO_SHORT',
    DESCRIPTION_TOO_LONG: 'DESCRIPTION_TOO_LONG',
    PRICE_TOO_LOW: 'PRICE_TOO_LOW',
    PRICE_TOO_HIGH: 'PRICE_TOO_HIGH',
    PRICE_INVALID: 'PRICE_INVALID',
    AMOUNT_TOO_LOW: 'AMOUNT_TOO_LOW',
    AMOUNT_TOO_HIGH: 'AMOUNT_TOO_HIGH',
    AMOUNT_INVALID: 'AMOUNT_INVALID',
    GROUP_CANNOT_ADD: 'GROUP_CANNOT_ADD',
    GROUP_CANNOT_REMOVE: 'GROUP_CANNOT_REMOVE'
  }
};
