export const MODAL_IDS = {
  AUTH: 'LOGIN_REGISTER_MODAL',
  NEW_PRODUCT: 'SELL_PRODUCT_MODAL'
};

export const GROUP_PERMISSIONS = {
  DELETE_USER: 'DELETE_USERS',
  DELETE_SELLER: 'DELETE_SELLER',
  DELETE_ADMIN: 'DELETE_ADMIN',
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  DELETE_USER_ITEM: 'DELETE_USER_ITEM',
  DELETE_SELLER_ITEM: 'DELETE_SELLER_ITEM',
  DELETE_ADMIN_ITEM: 'DELETE_ADMIN_ITEM',
  CHANGE_ROLES: 'CHANGE_ROLES',
  EDIT_SETTINGS: 'EDIT_SETTINGS'
};
